/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 webDesignIcon.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./img/webDesignIcon.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.53, 0]} scale={1.26}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[0, 0.13, -0.01]}
        scale={0.9}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.71, 0.05]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.004"]}
        position={[0, 0.63, 0.08]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.005"]}
        position={[-0.23, 0.95, 0.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.006"]}
        position={[-0.17, 0.95, 0.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.007"]}
        position={[-0.1, 0.95, 0.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.003"]}
        position={[0, 0.95, 0.08]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.003"]}
        position={[-0.59, 0.44, 0.11]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.001"]}
        position={[-0.59, 0.41, 0.12]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.005"]}
        position={[-0.69, 0.55, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.006"]}
        position={[-0.66, 0.55, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.007"]}
        position={[-0.63, 0.55, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.001"]}
        position={[-0.59, 0.55, 0.12]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.001"]}
        position={[-0.14, 0.59, 0.09]}
        scale={0.88}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.Material}
        position={[-0.14, 0.6, 0.1]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
        position={[-0.14, 0.49, 0.1]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.Material}
        position={[-0.14, 0.43, 0.1]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.Material}
        position={[-0.14, 0.76, 0.1]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[-0.14, 0.71, 0.1]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.003"]}
        position={[0.59, 0.67, 0.11]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Material.001"]}
        position={[0.59, 0.64, 0.12]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.005"]}
        position={[0.48, 0.78, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.006"]}
        position={[0.51, 0.78, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.007"]}
        position={[0.54, 0.78, 0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Material.001"]}
        position={[0.59, 0.78, 0.12]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.006"]}
        position={[-0.14, 0.63, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.001"]}
        position={[0.14, 0.4, 0.09]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials["Material.001"]}
        position={[0, 0.18, 0.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.002"]}
        position={[0.59, 0.67, 0.13]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.007"]}
        position={[-0.1, 0.54, 0.12]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.007"]}
        position={[-0.18, 0.54, 0.12]}
        rotation={[-Math.PI / 2, Math.PI / 4, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["Material.002"]}
        position={[-0.59, 0.44, 0.13]}
        rotation={[1.58, 0.03, 0]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials["Material.002"]}
        position={[-0.64, 0.44, 0.13]}
        rotation={[1.58, 0.03, 0]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials["Material.002"]}
        position={[-0.53, 0.44, 0.13]}
        rotation={[1.58, 0.03, 0]}
        scale={0.39}
      />
    </group>
  );
}

useGLTF.preload("./img/webDesignIcon.glb");
